version: '3.8'

services:
  api:
    build:
      context: .
      network: host
    ports:
      - "5000:5000"

# command: ["spark-shell"]

# command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
